name: booking_management_dashboard
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  responsive_builder: ^0.2.0+2
  cloud_firestore: ^0.13.5
  cupertino_icons: ^0.1.3
  websafe_svg: ^1.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icon_type_grid_selected.svg
    - assets/icon_type_grid_unselected.svg
    - assets/icon_type_list_selected.svg
    - assets/icon_type_list_unselected.svg
    - assets/logo.png
    - assets/pro.png
    - assets/profile.png